language: java

addons:
  sonarqube:
    organization: "sonarsource"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8
  
script:
- sonar-scanner
- mvn clean install sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
