language: java

addons:
  sonarqube:
    organization: "itchyknee-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8
  
script:
 - mvn clean install sonar:sonar -Dsonar.jacoco.reportPath=target/jacoco.exec

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
